# Generated by Django 5.0 on 2023-12-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sam_charles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
