# Generated by Django 5.0 on 2023-12-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam_charles', '0002_rename_songs_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
