# Generated by Django 5.0 on 2023-12-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam_charles', '0003_song_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
